// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2I-gTNaDwGfY1nvdR3CdGZyLTmbAld1Q',
    appId: '1:573068564766:web:85d439f2b51a84fedb510f',
    messagingSenderId: '573068564766',
    projectId: 'e-commerce-b5787',
    authDomain: 'e-commerce-b5787.firebaseapp.com',
    storageBucket: 'e-commerce-b5787.firebasestorage.app',
    measurementId: 'G-5P1L9PHKL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHiOV9S9cOt5chxtzWYygAyqeHxb3H4c',
    appId: '1:573068564766:android:14b7bb6853153a55db510f',
    messagingSenderId: '573068564766',
    projectId: 'e-commerce-b5787',
    storageBucket: 'e-commerce-b5787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwofjU2Gg1DSCw-nIxC9lZ4Wtj1vqWnbE',
    appId: '1:573068564766:ios:2efacb10523279d2db510f',
    messagingSenderId: '573068564766',
    projectId: 'e-commerce-b5787',
    storageBucket: 'e-commerce-b5787.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppApi26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2I-gTNaDwGfY1nvdR3CdGZyLTmbAld1Q',
    appId: '1:573068564766:web:805ac908ecddd656db510f',
    messagingSenderId: '573068564766',
    projectId: 'e-commerce-b5787',
    authDomain: 'e-commerce-b5787.firebaseapp.com',
    storageBucket: 'e-commerce-b5787.firebasestorage.app',
    measurementId: 'G-EYWBFBCMT8',
  );
}
